### ISSUE TITLE
Access memory used by module

### ISSUE THREAD

**Issue by NikVolf** [pepyakin/wasmi#25]
It does not matter if module exports, imports, declares own memory and does not exports, there should be a way to request memory the module instance is using while running

**Comment by pepyakin** [comment]
We can provide something like “default_memory(&self) → Option<MemRef>”

However, i think that we should document this is escape hatch, and the user might not find similar functionality in another execution engine

**Comment by NikVolf** [comment]
why is it escape hatch?
i don't think any meaningful interaction with module is possible without sharing the linear memory, and compilers are not obliged to produce module with exported memory

**Comment by NikVolf** [comment]
on the second thought, i realized that js api indeed provides no way to interact with such internal memory

**Comment by pepyakin** [comment]
> i don't think any meaningful interaction with module is possible without sharing the linear memory

Why not? Consider some module that have a function that do some pure computation: e.g. some argument in and result out. This computation requires some memory in form of a stack in linear memory. The stack is transient: that is, stack pointer starts with zero at the start of the computation and ends with zero at the end of the computation. 
So this is an example of meaningful interaction with a module that doesn't expose it's memory.

Second example: the module doesn't export a memory but provides an interface in form of exported functions, that user might use to set up some initial information and get results back. (In the end, your module doesn't have to have any memory at all and still might be able to do something useful)

But such kind of interaction might be inconvenient or not efficient or both. So for these kinds of problems we can provide this method `default_memory(&self) → Option<MemoryRef>`.

Why I'm calling this an escape hatch? Because it isn't required by the spec and this will certanly mean that some execution engines might not support this kind of interaction. And to not mislead users I want to clearly state that this is an escape hatch

**Comment by pepyakin** [comment]
> i realized that js api indeed provides no way to interact with such internal memory

Good point!

**Comment by pepyakin** [comment]
Closing tilll the spec come up with the official way to do this, at least in JS.
